### ISSUE TITLE
syntax error in code

### ISSUE THREAD

**Issue by RiyaUplenchwar** [Bouke/pathfinding#1]
hey... I tried to implement your code but I am getting syntax error at line like 300,306 etc. The syntax error is like " Non-ASCII character '\xef' in file main.py on line 306, but no encoding declared". I tried to remove the error but unable to do. plzz tell how to remove such syntax error. Thank you.

**Comment by Bouke** [comment]
I think this is due to the "√" and "ｘ" characters being used. You could replace those with simple ASCII symbols, like "v" and "x".

**Comment by RiyaUplenchwar** [comment]
I make the changes as u said.. After executing the code it gives value
error... Send you the pic of the execution.... thank you...
