### ISSUE TITLE
value error in code...

### ISSUE THREAD

**Issue by RiyaUplenchwar** [Bouke/pathfinding#2]
After making the changes in code... It started executing..Though it take long time to give the output but it gives the error as valueError... I tried removing it but still its giving error... Do check and resolve.. Sorry and Thank you..

**Comment by Bouke** [comment]
Ref; #1. I'm not sure what happens. Please not that the code is experimental and for your own experiments only. I don't have the time to resolve any issues that you run into, sorry.
